# Generated by Django 5.1.7 on 2025-04-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuxSpace', '0003_alter_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image12',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image13',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='LuxuryFeature',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
