# Generated by Django 5.1.7 on 2025-04-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuxSpace', '0004_remove_propertyimage_property_property_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
    ]
