# Generated by Django 5.1.7 on 2025-04-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuxSpace', '0006_alter_property_map_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='map_embed_url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
