# Generated by Django 5.1.7 on 2025-04-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuxSpace', '0007_alter_property_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
