# Generated by Django 5.1.7 on 2025-04-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuxSpace', '0010_property_icon1_property_icon2_property_icon3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='carousel_image1',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='carousel_image2',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='carousel_image3',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='carousel_image4',
            field=models.ImageField(blank=True, null=True, upload_to='properties/%Y/%m/%d/'),
        ),
    ]
