# Generated by Django 5.1.7 on 2025-04-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuxSpace', '0011_property_carousel_image1_property_carousel_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='old_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
